# Generated by Django 5.2.5 on 2025-10-27 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opettaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(default='', max_length=100)),
                ('puhelin', models.CharField(default='', max_length=20)),
            ],
            options={
                'ordering': ['nimi'],
            },
        ),
        migrations.CreateModel(
            name='Kurssi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nimi', models.CharField(default='', max_length=100)),
                ('laajuus', models.IntegerField()),
                ('opettaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.opettaja')),
            ],
            options={
                'ordering': ['nimi'],
            },
        ),
    ]
